### PR TITLE
Feature/export sector

### LINKED ISSUE #5: Export Sector
The ascent logbook does list the top crag only. To retrieve the sector it is necessary to read the details from the route page.

### PR DESCRIPTION
**Pull request by lordyavin**
Closing #5

### CODE REVIEW

**Comment by lordyavin** [comment]
@Mdemaillard please try the new feature

**Comment by Mdemaillard** [comment]
Hi Kai,
i tried installing python, downloading the master branch, and playing with
it but i am really at a loss, and have no idea what i'm doing :-)

I'm afraid i would need quite a few pointers to be able to help you
- what to install (python should be fine), selenium ? is that in python ?
in firefox ? do i need eclipse ?
- do i have to download some project and compile it ? it seems more complex
than the simple scripts i played with years ago
cheers,

Marc de Maillard

**Comment by lordyavin** [comment]
Steps:

1. Install python or create a fresh virtualenv (`python -m venv eightanu/.venv`)
  a. If using a virtualenv activate it: `./eightanu/.venv/Scripts/activate`
2. Install requirements: `pip install -r eightanu/requirements.txt`
3. Add eightanu/src to your PYTHONPATH
4. Run the script: `python eightanu/src/eightanu/cli.py`

**Comment by lordyavin** [comment]
Oh and you should checkout the branch feature/export_sector

**Pull request merged**
